# Generated by Django 3.1.7 on 2023-07-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(max_length=80, unique=True, verbose_name='member_id'),
        ),
    ]
