# Generated by Django 3.1.7 on 2023-08-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20230809_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=170),
        ),
    ]
