# Generated by Django 3.1.7 on 2023-08-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('workout', models.CharField(max_length=20)),
                ('set', models.IntegerField(default=5)),
                ('weight', models.IntegerField(max_length=200)),
                ('reps', models.IntegerField(max_length=200)),
                ('alone_or_group', models.IntegerField(max_length=1)),
            ],
        ),
    ]
