# Generated by Django 3.1.7 on 2023-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='alone_or_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
