# Generated by Django 3.1.7 on 2023-08-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20230809_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout',
            field=models.CharField(max_length=100),
        ),
    ]
