# Generated by Django 3.1.7 on 2023-08-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20230810_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkoutClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('start_time', models.TimeField(max_length=20)),
                ('end_time', models.TimeField(max_length=20)),
                ('class_pk', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='class_pk',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
