# Generated by Django 3.1.7 on 2023-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20230812_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkoutclass',
            name='contents',
            field=models.CharField(default='', max_length=100),
        ),
    ]
