# Generated by Django 3.1.7 on 2023-08-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_groupworkoutclass_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='set',
            field=models.IntegerField(default=0),
        ),
    ]
